### ISSUE TITLE
None to version 0.1.0 as Fast as Possible - Steven Wilcox

### ISSUE THREAD

**Issue by swilcox** [swilcox/swilcox-gitalk-comments#3]
https://swilcox.github.io/post/none_to_0_dot_1/ 

 defining your version number in one place.

**Comment by bcorfman** [comment]
I'm somewhat embarrassed that I've never delved into this issue. In some of my projects, version numbers proliferate as you describe, and I've sort of suffered with it. I'm going to bookmark this and come back to your solution with some of my longer-lived projects.
